insert into Soucastka values ('1','10','cervena')
insert into Soucastka values ('2','20','zelena')
insert into Soucastka values ('3','30','modra')
insert into Soucastka values ('4','40','zluta')
insert into Soucastka values ('12','40','cervena')
insert into Soucastka values ('13','30','modra')
insert into Soucastka values ('14','20','zelena')
insert into Soucastka values ('15','20','zluta')
insert into Soucastka values ('16','100','zluta')

insert into Dodavatel values('1','Franta','Studentská 3 , Liberec','Liberec')
insert into Dodavatel values('2','Karel','Franklinova 777, Liberec','Liberec')
insert into Dodavatel values('3','Pavel','Husova 33, Liberec','Liberec')
insert into Dodavatel values('4','Pepa','Husova 55, Jièín','Jièín')
insert into Dodavatel values('5','Jana','Liberecká 44, Praha','Praha')
insert into Dodavatel values('6','Eva','Pod Koželuhy 559, Jièín','Jièín')
insert into Dodavatel values('7','Lucie','Pražská 737, Nová Paka','Nová Paka')
insert into Dodavatel values('8','Pøemek','Brnìnská 7, Brno','Brno')
insert into Dodavatel values('9','Petra','Pøátelství 177, Valdice','Valdice')
insert into Dodavatel values('10','Klára','Mšenská 555, Jablonec nad Nisou','Jablonec nad Nisou')
UPDATE Dodavatel SET adresa='Pøátelství 177, Valdice' WHERE cisdod=9

insert into Dodava (cissou,cisdod) values('1','1')
insert into Dodava (cissou,cisdod) values('2','2')
insert into Dodava (cissou,cisdod) values('3','3')
insert into Dodava (cissou,cisdod) values('4','4')
insert into Dodava (cissou,cisdod) values('12','2')
insert into Dodava (cissou,cisdod) values('13','3')
insert into Dodava (cissou,cisdod) values('14','4')
insert into Dodava (cissou,cisdod) values('15','5')
insert into Dodava (cissou,cisdod) values('15','7')
insert into Dodava (cissou,cisdod) values('15','9')
insert into Dodava (cissou,cisdod) values('4','10')
insert into Dodava (cissou,cisdod) values('15','10')
insert into dodava (cisdod, cissou) VALUES (10, 12), (10,13)